import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Cards from "./componentes/cards";
import Contatos from "./contatos/contato";
import QuemSomos from "./quemSomos/quemSomos";
import Parceiros from "./parceiros/Parceiros";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>VITHELU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <code className={styles.topoFixo}>VITHELU</code>
        </div>
        <div className={styles.center}>
          <div className={styles.description}>
            <p>
              <code className={styles.code}>Demonstre o compromisso da sua empresa com a visão de excelência do seu ramo em cada interação.</code>
            </p>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/vithelu.svg"
            alt="Next.js Logo"
            width={400}
            height={200}
            priority
          />
        </div>
        <div className={styles.grid}>
          <Cards titulo={'Quem somos'} subtitulo='Veja quem somos' />
          <Cards titulo={'Parceiros'} subtitulo='Veja a opinião de nossos parceiros e clientes...' />
          <Cards titulo={'Contatos'} subtitulo='Entre em contato conosco...' />
        </div>
        <QuemSomos />
        <Parceiros />
        <Contatos />

      </main>
    </>
  );
}
